[package]
name = "pager-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
rand = "0.8.5"
sqlx = "0.6.3"
tokio = "1.28.2"
